/* Recognition drill items, for the drill page and the daily review.
 * Each: { q, code, options, answer, why, topic }. Finished find-the-bugs exercises add "which kind of bug is this line?" items. */
(function (root) {
  const RL = root.RL;
  RL.drill.push(
    /* ── reading ── */
    { topic: 'read', q: 'In Java terms, what does the «?» do here?', code: 'let n = parse(line)?;', options: ['A null check', 'A checked exception propagating to the caller', 'A ternary operator', 'An assertion'], answer: 1, why: 'If «parse» returned an error, the function returns that error right here. Otherwise «n» is the value.' },
    { topic: 'read', q: 'What does the «!» in «println!» tell you?', options: ['It never fails', 'It is a macro: code that writes code at compile time', 'It is negated', 'It panics on error'], answer: 1, why: 'A trailing «!» marks a macro call: «println!», «vec!», «format!», «writeln!».' },
    { topic: 'read', q: 'What does this print?', code: 'let len: usize = 300;\nprintln!("{}", len as u8);', options: ['300', '44', 'It panics', 'Compile error'], answer: 1, why: '«as» keeps the low bits without a word: 300 minus 256. «u8::try_from(len)» would return an error instead.' },
    { topic: 'read', q: 'The last line of a function has no semicolon. What is it?', code: 'fn double(x: i32) -> i32 {\n    x * 2\n}', options: ['A syntax error', 'The return value', 'A statement that is thrown away', 'A comment'], answer: 1, why: 'A final expression without a semicolon is the function\'s value. Adding the semicolon makes it return «()» instead.' },
    { topic: 'read', q: 'What does «#[derive(Debug)]» give a struct?', options: ['A debugger', 'Printing with «{:?}»', 'Logging', 'Equality checks'], answer: 1, why: 'Derive writes standard trait implementations for you, like Lombok. «Debug» is what «{:?}» needs.' },
    { topic: 'read', q: 'What does this create?', code: 'let buf = vec![0u8; 4096];', options: ['4096 zero bytes', 'A Vec holding the number 4096', 'A fixed-size array', 'An empty Vec with room for 4096'], answer: 0, why: '«vec![value; n]» repeats the value n times. «Vec::with_capacity(4096)» would be the empty one with room.' },
    { topic: 'read', q: 'Why is «\'outer» in this code not a lifetime?', code: "'outer: loop {\n    break 'outer;\n}", options: ['It is a lifetime', 'It is a label naming the loop', 'It is a char literal', 'It is a macro'], answer: 1, why: 'Loop labels use the same apostrophe as lifetimes. On a loop, and after «break» or «continue», it is only a name.' },

    /* ── ownership ── */
    { topic: 'own', q: 'Which of these is «Copy»?', options: ['«String»', '«Vec<u8>»', '«u32»', '«Box<u32>»'], answer: 2, why: 'Plain numbers, «bool» and «char» are copied on assignment. Anything that owns heap memory moves instead.' },
    { topic: 'own', q: 'What does «Arc::clone(&cfg)» cost?', options: ['A deep copy of the config', 'One atomic counter increment', 'Taking a lock', 'Nothing at all'], answer: 1, why: 'Cloning an «Arc» adds one owner to the count. The data itself is shared, not copied.' },
    { topic: 'own', q: 'Given «fn send(frame: Vec<u8>)», after «send(buf)» the caller…', options: ['can keep using «buf»', 'cannot use «buf» any more: it moved', 'has a copy', 'has a null'], answer: 1, why: 'A parameter without «&» takes ownership. «fn send(frame: &[u8])» would borrow instead.' },
    { topic: 'own', q: 'How long is this lock held (tokio Mutex)?', code: 'let _ = mutex.lock().await;', options: ['Until the end of the function', 'Not past this line: it is released immediately', 'Until «drop» is called', 'Until the next await'], answer: 1, why: '«let _ =» binds nothing, so the guard is dropped at the end of the statement. For std\'s Mutex the compiler rejects this; for tokio\'s it does not.' },
    { topic: 'own', q: '«&str» is to «String» as what is to «Vec<u8>»?', options: ['«&[u8]»', '«Box<u8>»', '«[u8; 4]»', '«&Vec<u8>»'], answer: 0, why: 'The borrowed view of owned bytes is a slice, «&[u8]». Functions that only read should take it.' },
    { topic: 'own', q: 'What happens here?', code: 'let name = String::from("José");\nlet s = &name[..4];', options: ['s is "José"', 's is "Jos"', 'It panics', 'Compile error'], answer: 2, why: '«é» is two bytes, so byte 4 lands inside it. Slicing a string at a non-character boundary panics.' },
    { topic: 'own', q: 'Where does a «MutexGuard» release its lock?', options: ['When «unlock()» is called', 'At the end of the scope it lives in, or at «drop(guard)»', 'When the garbage collector runs', 'At the next «.await»'], answer: 1, why: 'Rust has no «unlock()»: the guard releases the lock when it is dropped.' },

    /* ── borrowing ── */
    { topic: 'borrow', q: 'What does «&mut self» tell you about a method?', options: ['It may change the object', 'The object is copied', 'The object is consumed', 'It may return null'], answer: 0, why: '«&self» reads, «&mut self» changes, «self» consumes.' },
    { topic: 'borrow', q: 'A method is called «into_bytes». It most likely…', options: ['borrows the string', 'copies the string', 'consumes the string: the original is gone', 'returns a reference'], answer: 2, why: '«into_» methods take «self». In return they can reuse the buffer without copying.' },
    { topic: 'borrow', q: 'A method is called «to_vec». It most likely…', options: ['is free', 'allocates and copies', 'consumes the original', 'returns a view'], answer: 1, why: '«to_» means a new copy. «as_» would be a free view.' },
    { topic: 'borrow', q: 'In «fn longer<\'a>(a: &\'a str, b: &\'a str) -> &\'a str», what does «\'a» say?', options: ['The result lives as long as the program', 'The result cannot outlive either input', 'The function runs for a set time', 'The strings are copied'], answer: 1, why: 'A lifetime is a label tying references together, not a duration anyone chooses.' },
    { topic: 'borrow', q: 'What does «T: \'static» on «tokio::spawn» require of the task?', options: ['It runs forever', 'It owns its data: it borrows nothing short-lived', 'It is a static method', 'It cannot be cancelled'], answer: 1, why: 'The task may outlive the function that spawned it, so it cannot hold references into that function. Hence «move» and «Arc» before spawns.' },
    { topic: 'borrow', q: '«borrow_mut()» on a «RefCell» while a «borrow()» of it is still alive…', options: ['is a compile error', 'panics at run time', 'waits', 'silently copies'], answer: 1, why: '«RefCell» checks the borrow rules while running, so a conflict becomes a panic ("already borrowed").' },

    /* ── compiler errors ── */
    { topic: 'codes', q: 'Which error code means "you used a value after it moved"?', options: ['E0382', 'E0502', 'E0308', 'E0277'], answer: 0, why: 'E0382: borrow (or use) of moved value. Something took ownership earlier.' },
    { topic: 'codes', q: 'E0502 means…', options: ['a value was moved', 'a mutable borrow overlaps a shared one', 'mismatched types', 'a trait is missing'], answer: 1, why: 'Cannot borrow as mutable because it is also borrowed as immutable: finish reading before writing.' },
    { topic: 'codes', q: 'E0308 "mismatched types" at the end of a function most often means…', options: ['a stray semicolon on the last line', 'a missing «mut»', 'a moved value', 'a missing import'], answer: 0, why: 'The semicolon turned the return value into a statement, so the function produces «()».' },
    { topic: 'codes', q: 'E0277 "the trait bound is not satisfied" or "doesn\'t implement" usually means…', options: ['a type lacks a trait it needs (like «Debug»), or «?» is used where no error can be returned', 'two mutable borrows', 'a value moved', 'a lifetime is too short'], answer: 0, why: 'E0277 is about traits: printing without «Debug», «?» in a function returning «()», sending a non-«Send» type to another thread.' },
    { topic: 'codes', q: 'E0596 "cannot borrow as mutable" on «c.bump()» means…', options: ['«c» was not declared «let mut»', '«bump» takes «self»', '«c» was moved', '«bump» is private'], answer: 0, why: 'Calling a «&mut self» method needs a variable declared «mut».' },
    { topic: 'codes', q: 'E0597 "does not live long enough" means…', options: ['a reference outlives the value it points into', 'a value was moved', 'a thread panicked', 'a type is too large'], answer: 0, why: 'The value is dropped while something still refers to it.' },
    { topic: 'codes', q: 'E0373 on «thread::spawn(|| ...)» is fixed by…', options: ['adding «move» so the closure owns what it uses', 'adding «mut»', 'adding «unsafe»', 'adding a lifetime'], answer: 0, why: 'The thread may outlive the function, so the closure must own its data, not borrow it.' },

    /* ── errors ── */
    { topic: 'errors', q: 'What does «.ok()» do to a «Result»?', options: ['Panics on «Err»', 'Turns it into an «Option», throwing the error away', 'Logs the error', 'Retries'], answer: 1, why: 'The error is discarded. Fine when failure truly does not matter; otherwise, who finds out?' },
    { topic: 'errors', q: 'A failed parse of an «i32» with «.unwrap_or_default()» gives…', options: ['a panic', '0', '«None»', '-1'], answer: 1, why: 'The error silently becomes the type\'s default. No crash, no log, a made-up number.' },
    { topic: 'errors', q: 'A thread panics. What happens to the rest of the program?', options: ['Everything stops', 'It keeps running; the panic only shows up through «join()»', 'The panic is rethrown in main automatically', 'The operating system kills the process'], answer: 1, why: 'Only that thread (or tokio task) dies. A service can look healthy with its worker dead.' },
    { topic: 'errors', q: 'Which «unwrap» deserves a comment?', options: ['«Regex::new("^MSH").unwrap()» at startup', '«String::from_utf8(frame).unwrap()» on bytes from a TCP peer', '«parse("1").unwrap()» in a test', '«v.first().unwrap()» right after «if v.is_empty() { return; }»'], answer: 1, why: 'The peer decides what bytes arrive. One Windows-1252 sender and the connection task panics.' },
    { topic: 'errors', q: 'What is «thiserror» for?', options: ['Defining a readable error enum for a library', 'Catching panics', 'Retrying failed calls', 'Logging'], answer: 0, why: '«#[derive(Error)]» plus «#[error("...")]» messages and «#[from]» conversions. Applications usually use anyhow with «.context(...)».' },
    { topic: 'errors', q: 'What does «.context("reading config")?» add (anyhow)?', options: ['A retry', 'A message saying what the program was doing when it failed', 'A panic', 'A default value'], answer: 1, why: 'The error keeps its cause and gains the context, so the log line says both.' },

    /* ── enums and traits ── */
    { topic: 'traits', q: 'A variant is added to an enum. Which matches will the compiler flag?', options: ['All of them', 'Only those without a «_ =>» catch-all', 'Only those with a catch-all', 'None: new variants are always allowed'], answer: 1, why: 'A catch-all arm covers the new variant silently. That is exactly the match to look at in the review.' },
    { topic: 'traits', q: 'How do you read «impl Sink for FileSink»?', options: ['FileSink extends Sink', 'FileSink implements Sink', 'Sink wraps FileSink', 'FileSink is a generic parameter'], answer: 1, why: 'A trait is an interface; «impl Trait for Type» is «implements».' },
    { topic: 'traits', q: 'A list that mixes two different «Sink» implementations has type…', options: ['«Vec<impl Sink>»', '«Vec<S> where S: Sink»', '«Vec<Box<dyn Sink>>»', '«Vec<Sink>»'], answer: 2, why: 'Generics pick one concrete type. Mixed implementations need trait objects behind a pointer.' },
    { topic: 'traits', q: 'Why does «let n: u8 = 300u16.into();» not compile?', options: ['«into» is only for strings', 'There is no «From<u16> for u8»: the conversion could lose information', 'u16 is not Copy', 'It needs «mut»'], answer: 1, why: '«From» exists only for lossless conversions. «u8::try_from» is the checked one; «as» truncates without asking.' },

    /* ── iterators ── */
    { topic: 'iter', q: 'After «for x in v { .. }», can you still use «v»?', options: ['Yes', 'No: «for x in v» consumes it; «for x in &v» borrows', 'Only if v is a Vec', 'Only in release builds'], answer: 1, why: '«for x in v» is «into_iter()», which takes ownership.' },
    { topic: 'iter', q: 'What does this collect into?', code: 'let r: Result<Vec<u16>, _> = ["1", "x", "3"].iter().map(|s| s.parse::<u16>()).collect();', options: ['Ok([1, 3])', 'Err(..) for the "x"', 'Ok([1, 0, 3])', 'It panics'], answer: 1, why: 'Collecting Results into one Result stops at the first error.' },
    { topic: 'iter', q: '«filter(..).count() > 0» on a big collection is better written as…', options: ['«.all(..)»', '«.any(..)»', '«.find(..).unwrap()»', '«.collect::<Vec<_>>().len() > 0»'], answer: 1, why: '«any» stops at the first match instead of walking everything.' },

    /* ── shared state ── */
    { topic: 'shared', q: 'Why is «Arc<Vec<u8>>» read-only?', options: ['Vec is immutable', 'An «Arc» hands out shared access; changing shared data needs a lock or an atomic inside', 'Arc copies on write', 'It is not read-only'], answer: 1, why: 'Shared means read-only (the Borrowing module). Hence «Arc<Mutex<T>>».' },
    { topic: 'shared', q: 'Two methods lock mutex A then B, and B then A. What can happen?', options: ['A compile error', 'A deadlock under load', 'A panic', 'Nothing: Rust prevents it'], answer: 1, why: 'Rust prevents data races, not deadlocks. Locks must be taken in one agreed order.' },
    { topic: 'shared', q: 'E0277 "Rc<..> cannot be sent between threads safely" is fixed by…', options: ['unsafe', 'switching to Arc', 'adding move', 'cloning the Rc'], answer: 1, why: '«Arc» is the thread-safe version of «Rc».' },

    /* ── async ── */
    { topic: 'async', q: '«send(frame);» where send is an «async fn», with no «.await». What happens?', options: ['It sends in the background', 'Nothing: the future is built and dropped', 'It blocks', 'It panics'], answer: 1, why: 'Futures are lazy, like a Mono nobody subscribed to. rustc warns about it.' },
    { topic: 'async', q: 'Which of these blocks the Tokio runtime?', options: ['«tokio::time::sleep(d).await»', '«std::thread::sleep(d)» inside an async fn', '«rx.recv().await»', '«spawn_blocking(f)»'], answer: 1, why: 'A blocking call holds the worker thread, freezing every task scheduled on it.' },
    { topic: 'async', q: 'Dropping a «JoinHandle» …', options: ['cancels the task', 'detaches it: the task keeps running unsupervised', 'panics', 'waits for the task'], answer: 1, why: 'Use «abort()» to cancel. And a dropped handle means the task\'s failures are invisible.' },
    { topic: 'async', q: 'A tokio «Mutex» guard held across a 30 s network await means…', options: ['a compile error', 'every other task wanting the lock waits 30 s', 'the lock is released during the await', 'a deadlock always'], answer: 1, why: 'It compiles; it just makes everyone as slow as the slowest peer.' },

    /* ── channels and select! ── */
    { topic: 'chan', q: 'Why prefer «mpsc::channel(n)» over «unbounded_channel()»?', options: ['It is faster', 'A full bounded channel makes senders wait: backpressure instead of unlimited memory', 'Unbounded channels lose messages', 'Bounded channels never block'], answer: 1, why: 'With a slow consumer, an unbounded queue just grows.' },
    { topic: 'chan', q: 'A «while let Some(x) = rx.recv().await» loop never ends. Most likely…', options: ['the channel is full', 'some sender is still alive somewhere', 'recv is not cancel-safe', 'the buffer is too small'], answer: 1, why: '«recv» returns «None» only when every sender has been dropped.' },
    { topic: 'chan', q: 'In «select!», what happens to the futures that lose the race?', options: ['They keep running', 'They are dropped mid-flight', 'They are retried', 'They panic'], answer: 1, why: 'Whatever they had half done is lost, unless they are cancel-safe.' },
    { topic: 'chan', q: 'Which branch is a trap?', options: ['«Some(msg) = rx.recv() =>»', '«Ok((conn, _)) = listener.accept() =>»', '«_ = stop.changed() =>»', '«_ = sleep(d) =>»'], answer: 1, why: 'One accept error fails the pattern, the branch switches off, and the loop silently stops accepting.' },
    { topic: 'chan', q: 'Which read is safe to race inside «select!»?', options: ['«read_exact»', '«read_to_end»', '«read_buf» into a buffer kept outside the loop', '«write_all»'], answer: 2, why: 'With «read_buf», the bytes already read live in your buffer, not in the dropped future.' },

    /* ── networking ── */
    { topic: 'net', q: 'A client writes two MLLP frames. The server calls «read» once. It gets…', options: ['exactly one frame', 'any amount: part of a frame, one, or both', 'always both', 'an error'], answer: 1, why: 'TCP is a byte stream. Framing is your job: a buffer plus a frame parser.' },
    { topic: 'net', q: 'A peer vanishes without closing (a VPN drops). A plain «read().await» …', options: ['returns 0', 'returns an error at once', 'waits forever', 'panics'], answer: 2, why: 'Only a read timeout or TCP keepalive notices a half-open connection.' },
    { topic: 'net', q: 'In «info!(peer = %addr, "accepted")», what does «%» mean?', options: ['modulo', 'record the field with Display', 'record it with Debug', 'a format width'], answer: 1, why: '«%» is Display, «?» is Debug.' },
    { topic: 'net', q: 'When should a relay send the ACK?', options: ['As soon as bytes arrive', 'After the message is safely forwarded or stored', 'Before reading the message', 'Never'], answer: 1, why: 'An ACK tells the sender it may delete its copy. ACK early, fail later, and the message is lost.' },

    /* ── crates ── */
    { topic: 'crates', q: 'In Cargo.toml, what does «serde = "1.0.200"» allow?', options: ['exactly 1.0.200', '1.0.200 or any later 1.x', 'any version at all', '1.0.x only'], answer: 1, why: 'A plain version is a range up to the next breaking version. «Cargo.lock» records which one was actually built.' },
    { topic: 'crates', q: 'Bumping «tonic = "0.12"» to «"0.13"»: how big a change is that?', options: ['a patch release', 'a breaking upgrade: before 1.0 the second number is the breaking one', 'nothing changes until Cargo.lock is deleted', 'only new features'], answer: 1, why: 'For 0.x crates, 0.12 to 0.13 may break the API, so expect code changes to go with it.' },
    { topic: 'crates', q: 'The compiler says an item was "configured out" and names a feature. Where is the fix?', options: ['in the code that uses it', 'in Cargo.toml: turn that feature on for the dependency', 'update the Rust toolchain', 'add a «use» line'], answer: 1, why: 'The code exists in the crate but is switched off. «features = ["attributes"]» (or whichever the message names) switches it on.' },
    { topic: 'crates', q: 'What does «pub(crate)» on a function mean?', options: ['public to everyone', 'usable anywhere in this crate, invisible to other crates', 'usable only in this module', 'usable only in tests'], answer: 1, why: 'It is the right default for internals: other code in the crate can call it, and no other crate can start depending on it.' },
    { topic: 'crates', q: 'Which check still runs in a release build?', options: ['«debug_assert!(len < MAX)»', '«assert!(len < MAX)»', 'neither', 'both'], answer: 1, why: '«debug_assert!» is compiled out of release builds. Checking outside input needs a real «if» that returns an error.' },
    { topic: 'crates', q: 'What does «unreachable!()» do if the line runs after all?', options: ['nothing', 'logs a warning', 'panics', 'returns «None»'], answer: 2, why: 'It is a panic with "entered unreachable code". On a value from another system, it is a crash waiting for its input.' },

    /* ── wire formats ── */
    { topic: 'wire', q: 'serde parses «{"route": "lab-a", "colur": "blue"}» into a struct with only «route». By default…', options: ['it fails: unknown field', 'the extra field is ignored', 'it panics', '«colur» becomes «None»'], answer: 1, why: 'serde ignores unknown fields unless the struct has «#[serde(deny_unknown_fields)]», which is how a misspelt config key goes unnoticed.' },
    { topic: 'wire', q: 'In prost\'s generated code, what type is a nested message field such as «header»?', options: ['«Header»', '«Option<Header>»', '«Box<Header>»', '«&Header»'], answer: 1, why: 'Any message field may be absent, so it is an «Option». «.unwrap()» on it crashes on a sender that left it out.' },
    { topic: 'wire', q: 'A proto enum field holds 9, a value this build does not know. prost\'s generated getter returns…', options: ['9', 'the default (zero) variant', 'an error', 'it panics'], answer: 1, why: 'The getter is «Kind::try_from(self.kind).unwrap_or(Kind::default())». «Kind::try_from» keeps the difference between unknown and unset.' },
    { topic: 'wire', q: 'A destination is down. Which tonic status tells the caller to retry later?', options: ['«Status::internal»', '«Status::invalid_argument»', '«Status::unavailable»', '«Status::not_found»'], answer: 2, why: '«UNAVAILABLE» means a passing problem, retry with backoff. «INTERNAL» says "a bug here", and callers usually do not retry it.' },
    { topic: 'wire', q: 'A server-stream task sends acks with «let _ = tx.send(ack).await;» in a loop. After the client disconnects…', options: ['the task stops', 'the task runs forever, sending into nothing', 'tonic kills the task', 'it panics'], answer: 1, why: 'The failed send is the only signal that the client left, and «let _ =» throws it away. Break out of the loop when «send» fails.' },
    { topic: 'wire', q: 'A test ends with «let _ = relay.forward(..).await;» and has no assert. What does it prove?', options: ['that forwarding works', 'that forwarding retries', 'only that «forward» does not panic', 'nothing: it cannot compile'], answer: 2, why: 'A test proves only what it asserts. Ask what would have to break for it to fail.' },
  );
})(typeof globalThis !== 'undefined' ? globalThis : this);
