/* Pattern taxonomy (used by the drill and the pattern finder) and the home-page roadmap. */
(function () {
  const D = window.DSA;
  // key → { label, signal (how to recognise it), confuse (patterns it gets mistaken for), lesson }
  D.patterns = {
    'hash-lookup': { label: 'Hash map lookup', lesson: 'hashing-patterns', confuse: ['two-pointers', 'counting', 'prefix-sum'],
      signal: 'You need to know instantly whether you have **seen** something (a value, its complement, a state) earlier in a single pass.' },
    'counting': { label: 'Frequency counting', lesson: 'hashing-patterns', confuse: ['hash-lookup', 'sliding-window', 'heap-topk'],
      signal: 'The answer depends on **how many times** things occur, not where; anagrams, "most frequent", "appears more than n/2".' },
    'prefix-sum': { label: 'Prefix sums', lesson: 'prefix-sums', confuse: ['sliding-window', 'two-pointers', 'hash-lookup'],
      signal: '**Subarray sums** (especially with negative numbers) or many **range-sum queries**: sum(i..j) = prefix[j+1] − prefix[i].' },
    'two-pointers': { label: 'Two pointers', lesson: 'two-pointers', confuse: ['sliding-window', 'binary-search', 'hash-lookup'],
      signal: '**Sorted** input (or sortable) and a pair/triple condition; or in-place rearranging with a read and a write pointer.' },
    'sliding-window': { label: 'Sliding window', lesson: 'sliding-window', confuse: ['two-pointers', 'prefix-sum', 'dp-1d'],
      signal: 'Longest/shortest **contiguous** subarray or substring satisfying a condition that stays valid as the window shrinks.' },
    'stack': { label: 'Stack', lesson: 'stacks', confuse: ['mono-stack', 'tree-dfs', 'backtracking'],
      signal: '**Nesting / matching** (brackets, tags), undo, or evaluating expressions: the most recent open thing is the first to close.' },
    'mono-stack': { label: 'Monotonic stack / deque', lesson: 'monotonic-stack', confuse: ['stack', 'two-pointers', 'heap-topk'],
      signal: '"**Next greater/smaller** element", spans, histogram areas, or window max/min in O(n).' },
    'binary-search': { label: 'Binary search', lesson: 'binary-search', confuse: ['two-pointers', 'bs-answer', 'bst'],
      signal: '**Sorted** (or rotated-sorted) data and you need a position; anything that screams O(log n).' },
    'bs-answer': { label: 'Binary search on the answer', lesson: 'binary-search-answer', confuse: ['binary-search', 'greedy', 'dp-1d'],
      signal: '"Minimum **capacity/speed/time** such that it’s feasible": feasibility is monotone in the answer, and checking one candidate is easy.' },
    'linked-list': { label: 'Linked-list rewiring', lesson: 'linked-lists', confuse: ['fast-slow', 'two-pointers', 'stack'],
      signal: 'Reverse, merge, reorder or splice nodes **in place**: a dummy head and careful next-pointer updates.' },
    'fast-slow': { label: 'Fast & slow pointers', lesson: 'linked-lists', confuse: ['linked-list', 'two-pointers', 'hash-lookup'],
      signal: '**Cycle** detection, the **middle** of a list, or "k-th from the end" in one pass with O(1) space.' },
    'tree-dfs': { label: 'Tree DFS (recursion)', lesson: 'tree-dfs', confuse: ['tree-bfs', 'backtracking', 'bst'],
      signal: 'The answer for a node is built from its **children’s answers**: depth, diameter, path sums, balanced, subtree checks.' },
    'tree-bfs': { label: 'Tree BFS (level order)', lesson: 'tree-bfs', confuse: ['tree-dfs', 'bfs-shortest', 'graph-traversal'],
      signal: 'Anything **per level**: level order, right side view, zigzag, minimum depth, nearest leaf.' },
    'bst': { label: 'BST property', lesson: 'bst', confuse: ['tree-dfs', 'binary-search', 'tree-bfs'],
      signal: 'The tree is a **binary search tree**: in-order is sorted, and each node bounds its subtrees (validate, k-th smallest, LCA).' },
    'heap-topk': { label: 'Heap / top-K', lesson: 'heaps', confuse: ['counting', 'two-heaps', 'binary-search'],
      signal: '"**K largest/smallest/closest/most frequent**", or repeatedly taking the best item from a changing set.' },
    'two-heaps': { label: 'Two heaps', lesson: 'heaps', confuse: ['heap-topk', 'binary-search', 'bst'],
      signal: 'A running **median** (or any split point) over a stream: max-heap for the low half, min-heap for the high half.' },
    'kway-merge': { label: 'K-way merge', lesson: 'heaps', confuse: ['heap-topk', 'two-pointers', 'linked-list'],
      signal: 'Merge **k sorted** lists/arrays, or the k-th smallest across sorted sources: a heap of the current heads.' },
    'backtracking': { label: 'Backtracking', lesson: 'backtracking', confuse: ['dp-1d', 'graph-traversal', 'knapsack'],
      signal: 'Generate **all** subsets/permutations/combinations/boards, with small n (≤ ~15–20) and constraints to prune on.' },
    'graph-traversal': { label: 'Graph DFS/BFS (flood fill)', lesson: 'graph-basics', confuse: ['bfs-shortest', 'union-find', 'tree-dfs'],
      signal: '**Connected regions** in a grid or graph: islands, reachability, marking what touches the border.' },
    'bfs-shortest': { label: 'BFS shortest path', lesson: 'graph-basics', confuse: ['graph-traversal', 'dijkstra', 'dp-2d'],
      signal: '**Fewest steps/moves** where every move costs the same: grids, word ladders, multi-source spread (rotting oranges).' },
    'topo-sort': { label: 'Topological sort', lesson: 'topological-sort', confuse: ['graph-traversal', 'union-find', 'dijkstra'],
      signal: '**Dependencies / prerequisites / ordering** constraints, or detecting a cycle in a directed graph.' },
    'union-find': { label: 'Union-Find', lesson: 'union-find', confuse: ['graph-traversal', 'topo-sort', 'mst'],
      signal: 'Dynamic **connectivity**: merging groups, counting components, "does this edge create a cycle?" in an undirected graph.' },
    'dijkstra': { label: 'Dijkstra (weighted shortest path)', lesson: 'dijkstra', confuse: ['bfs-shortest', 'dp-2d', 'mst'],
      signal: 'Cheapest path with **non-negative weights**, or "minimize the maximum" along a path.' },
    'mst': { label: 'Minimum spanning tree', lesson: 'mst', confuse: ['dijkstra', 'union-find', 'greedy'],
      signal: 'Connect **all** points/nodes with minimum total cost.' },
    'dp-1d': { label: '1-D dynamic programming', lesson: 'dp-intro', confuse: ['greedy', 'backtracking', 'sliding-window'],
      signal: 'Count ways / min cost / max value where the choice at step i depends on a few **earlier results**; brute force recursion repeats subproblems.' },
    'dp-2d': { label: '2-D / string DP', lesson: 'dp-2d', confuse: ['dp-1d', 'backtracking', 'bfs-shortest'],
      signal: '**Two sequences** (LCS, edit distance), a **grid** of paths, or intervals i..j.' },
    'knapsack': { label: 'Knapsack DP', lesson: 'dp-2d', confuse: ['backtracking', 'dp-1d', 'greedy'],
      signal: 'Choose a **subset** hitting a target sum/capacity (partition, target sum, coin change II).' },
    'greedy': { label: 'Greedy', lesson: 'greedy', confuse: ['dp-1d', 'intervals', 'heap-topk'],
      signal: 'A **locally best** choice never hurts (you can argue by exchange), often after sorting; reach, fuel, jumps.' },
    'intervals': { label: 'Intervals (sort + sweep)', lesson: 'intervals', confuse: ['greedy', 'heap-topk', 'prefix-sum'],
      signal: 'Ranges [start, end]: **merge, insert, overlaps, rooms**; sort by start or end, then sweep.' },
    'trie': { label: 'Trie', lesson: 'tries', confuse: ['hash-lookup', 'backtracking', 'binary-search'],
      signal: '**Prefix** queries over many words, autocomplete, or searching many words in a grid at once.' },
    'bits': { label: 'Bit manipulation', lesson: 'bits', confuse: ['hash-lookup', 'counting', 'dp-1d'],
      signal: 'XOR cancels pairs, **O(1) space** tricks, powers of two, subsets as bitmasks.' },
    'matrix': { label: 'Matrix & math tricks', lesson: 'math-geometry', confuse: ['bits', 'graph-traversal', 'two-pointers'],
      signal: 'Rotate, spiral, transpose, **in-place** marking, fast power, overflow-safe arithmetic: known tricks, not search.' },
    'design': { label: 'Design (map + list)', lesson: 'linked-lists', confuse: ['heap-topk', 'hash-lookup', 'stack'],
      signal: 'Build a data structure with **O(1)** operations: LRU cache, min stack, get-random, time-keyed store.' },
  };

  // Home-page roadmap: [column, row] per module, and prerequisite edges.
  D.roadmap = {
    pos: {
      start: [2.5, 0], java: [2.5, 1], hashing: [2.5, 2],
      'two-pointers': [1.5, 3], stack: [3.5, 3],
      'sliding-window': [0.5, 4], 'binary-search': [2.5, 4], 'linked-list': [4.5, 4],
      trees: [2.5, 5],
      tries: [0.5, 6], heaps: [2.5, 6], backtracking: [4.5, 6],
      greedy: [1, 7], graphs: [3.5, 7], 'dp-1d': [5, 7],
      'weighted-graphs': [2.5, 8], 'dp-2d': [4.2, 8], bits: [5.6, 8.9],
    },
    edges: [
      ['start', 'java'], ['java', 'hashing'], ['hashing', 'two-pointers'], ['hashing', 'stack'],
      ['two-pointers', 'sliding-window'], ['two-pointers', 'binary-search'], ['two-pointers', 'linked-list'],
      ['binary-search', 'trees'], ['linked-list', 'trees'], ['stack', 'trees'],
      ['trees', 'tries'], ['trees', 'heaps'], ['trees', 'backtracking'],
      ['heaps', 'greedy'], ['backtracking', 'graphs'], ['backtracking', 'dp-1d'],
      ['heaps', 'weighted-graphs'], ['graphs', 'weighted-graphs'], ['graphs', 'dp-2d'], ['dp-1d', 'dp-2d'], ['dp-1d', 'bits'],
    ],
  };
})();
