/* Recognition drill items, for the drill page and the daily review. Each: { q, options, answer, why, topic } */
(function (root) {
  const BL = root.BL;
  BL.drill.push(
    /* ── requests ── */
    { topic: 'requests', q: 'A client times out at 2 s. The server commits at 2.3 s. What did the user see?', options: ['Success', 'An error, although the work was done', 'Nothing until the retry', 'A partial success'], answer: 1, why: 'The client gave up before the commit. The server, not told to stop, finished anyway.' },
    { topic: 'requests', q: 'Which operation is idempotent?', options: ['«balance = balance - 500»', '«INSERT INTO charges (amount) VALUES (500)»', '«status = \'SHIPPED\' WHERE id = 7»', '"send the receipt email"'], answer: 2, why: 'Setting a value to a constant has the same effect however many times it runs.' },
    { topic: 'requests', q: 'A retry arrives while the first attempt with the same idempotency key is still running. What should the server answer?', options: ['200 with a new charge', '409 Conflict', '404 Not Found', '500'], answer: 1, why: 'The key is in progress; the client should wait and retry with the same key. The IETF draft and Stripe both use 409 here.' },
    { topic: 'requests', q: 'Where must the processed-event id be recorded?', options: ['In Redis, for speed', 'In the same database transaction as the effect', 'In the consumer\'s memory', 'In the Kafka offset'], answer: 1, why: 'Otherwise a crash between the two either repeats the effect or loses it.' },
    { topic: 'requests', q: 'What is the default deadline on a gRPC call?', options: ['30 s', '15 s', 'None: it can wait forever', '1 s'], answer: 2, why: 'gRPC sets no deadline unless the client does. Always set one.' },
    { topic: 'requests', q: 'A page fans out to 100 calls, each slow 1% of the time. Roughly how many pages are slow?', options: ['1%', '10%', 'About 63%', '100%'], answer: 2, why: '1 − 0.99^100 is about 0.63, the example in The Tail at Scale.' },
    { topic: 'requests', q: 'How do you get the p99 across 40 hosts?', options: ['Average the 40 p99s', 'Take the largest p99', 'Merge the histograms, then take the quantile', 'Take the median p99'], answer: 2, why: 'Percentiles do not average; you need the combined distribution.' },
    { topic: 'requests', q: 'A closed-loop load test reports a low p99 even though the server stalls for 2 s at a time. Why?', options: ['The stalls are rare', 'Coordinated omission: the generator stops sending during the stall', 'The server caches responses', 'Network latency hides it'], answer: 1, why: 'It waits for each response before sending the next, so the requests that would have hit the stall are never sent.' },

    /* ── dependencies ── */
    { topic: 'deps', q: '400 requests/s, and a dependency slows from 50 ms to 2 s. How many calls are in flight?', options: ['20', '200', '400', '800'], answer: 3, why: 'Little\'s law: 400/s × 2 s = 800.' },
    { topic: 'deps', q: 'What is a bulkhead?', options: ['A retry policy', 'A separate, bounded pool per dependency', 'A circuit breaker', 'A cache'], answer: 1, why: 'It confines a slow dependency to its own pool so it cannot starve the rest.' },
    { topic: 'deps', q: 'Five layers each try a call 3 times. The database fails. How many attempts reach it per user request?', options: ['3', '15', '125', '243'], answer: 3, why: '3^5 = 243. Retry at one layer only.' },
    { topic: 'deps', q: 'Which does exponential backoff with jitter not do?', options: ['Spread retries in time', 'Stop clients retrying in lockstep', 'Cap the total extra load', 'Delay the first retry'], answer: 2, why: 'Each client still makes every attempt. A retry budget caps the load.' },
    { topic: 'deps', q: 'A short slowdown is over, but the dependency still serves only abandoned requests. Name it.', options: ['A deadlock', 'A metastable failure', 'A stampede', 'A split brain'], answer: 1, why: 'Stable in the bad state: retries and dead work keep it overloaded with no remaining cause.' },
    { topic: 'deps', q: 'What lets a dependency skip requests whose callers already gave up?', options: ['A bigger queue', 'The caller\'s deadline travelling with the request', 'Auto-scaling', 'A circuit breaker on the dependency'], answer: 1, why: 'With the deadline it can drop expired work instead of serving it.' },
    { topic: 'deps', q: 'Resilience4j circuit breaker: how many calls must it see before it can open, by default?', options: ['1', '10', '50', '100'], answer: 3, why: 'minimumNumberOfCalls is 100 by default, with a 50% failure-rate threshold over a window of 100.' },

    /* ── caching ── */
    { topic: 'caching', q: 'Redis\'s default «maxmemory-policy»?', options: ['«allkeys-lru»', '«volatile-lru»', '«noeviction»', '«allkeys-lfu»'], answer: 2, why: 'With «noeviction», writes fail once the limit is reached. Set a policy for a cache.' },
    { topic: 'caching', q: 'Cache-aside, write path. The usual order?', options: ['Update the cache, then the database', 'Update the database, then delete the key', 'Delete the key, then never touch it again', 'Update both in parallel'], answer: 1, why: 'The next reader refills from the database; a delete has no ordering race between writers.' },
    { topic: 'caching', q: 'One rebuild, and nobody waits. Which technique?', options: ['A distributed lock', 'Single-flight per instance', 'Stale-while-revalidate', 'A longer TTL'], answer: 2, why: 'The old value is served while one background refresh runs.' },
    { topic: 'caching', q: 'The database spikes 60 s after every deploy. First suspect?', options: ['A slow query', 'All keys cached at once with the same TTL', 'Redis eviction', 'Connection pool size'], answer: 1, why: 'They expire together. Add TTL jitter and warm the cache.' },
    { topic: 'caching', q: 'Why does a single very hot key not get faster with more Redis Cluster nodes?', options: ['Clusters are slower', 'The key lives in one hash slot on one node', 'Replication lag', 'TTL expiry'], answer: 1, why: 'Sharding spreads keys, not one key. Use an in-process cache or copies of the key.' },
    { topic: 'caching', q: 'Lettuce\'s default timeout, if you set none?', options: ['100 ms', '1 s', '15 s', '60 s'], answer: 3, why: 'During a Redis outage that is up to a minute per request. Set milliseconds.' },
    { topic: 'caching', q: 'Redis returns after an outage. What happens next?', options: ['Everything is back to normal', 'It is empty, so the database takes a second wave of misses', 'Redis replays the missed writes', 'Clients reconnect slowly but nothing else'], answer: 1, why: 'A cold cache means a low hit rate until it refills. Warm it or ramp traffic.' },

    /* ── messaging ── */
    { topic: 'messaging', q: 'Kafka guarantees order…', options: ['across the whole topic', 'within a partition', 'within a consumer group', 'only with transactions'], answer: 1, why: 'Key by the entity whose order matters.' },
    { topic: 'messaging', q: 'What removes a live but slow consumer from its group?', options: ['«session.timeout.ms»', '«max.poll.interval.ms»', '«heartbeat.interval.ms»', '«auto.commit.interval.ms»'], answer: 1, why: 'Missing poll() for longer than max.poll.interval.ms. The session timeout covers dead processes.' },
    { topic: 'messaging', q: 'Default «partition.assignment.strategy» in current Java clients uses which assignor?', options: ['CooperativeStickyAssignor', 'RangeAssignor (eager)', 'RoundRobinAssignor', 'the broker\'s uniform assignor'], answer: 1, why: 'The list is [Range, CooperativeSticky]; range is used until you remove it.' },
    { topic: 'messaging', q: 'What does «group.instance.id» do?', options: ['Enables exactly once', 'Makes the member static: quick restarts do not trigger rebalances', 'Sets the partition count', 'Pins a consumer to a broker'], answer: 1, why: 'A static member does not leave on shutdown; within the session timeout it gets its partitions back.' },
    { topic: 'messaging', q: 'Retry topics keep the partition moving. What do they cost?', options: ['Nothing', 'Per-key ordering', 'Durability', 'Throughput'], answer: 1, why: 'A retried record is processed after later records with the same key.' },
    { topic: 'messaging', q: 'A downstream is down for 10 minutes. Best handling in the consumer?', options: ['Retry 3 times, then dead-letter', 'Skip and log', 'Pause and retry with backoff, keeping order', 'Restart the consumer'], answer: 2, why: 'Every record would fail; the data is fine. Dead-lettering would fill the DLQ with healthy records.' },
    { topic: 'messaging', q: 'Spring Kafka «DefaultErrorHandler» with no recoverer: a record fails every time. Result?', options: ['Retried forever', 'Logged and skipped after 10 attempts', 'Sent to «-dlt»', 'The container stops'], answer: 1, why: 'The default recoverer only logs. Configure a DeadLetterPublishingRecoverer.' },
  );
})(typeof globalThis !== 'undefined' ? globalThis : this);
